language: generic
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
env:
  global:
    - FLUTTER_CHANNEL=stable
install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get
cache:
  directories:
  - $HOME/.pub-cache

build: &build
    name: "Build APK"
    language: android
    jdk:
      - oraclejdk8
    android:
      components:
        - tools
        - tools # See (https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
        - platform-tools
        - build-tools-28.0.3
        - android-27 # Breaks the build if not present (https://github.com/flutter/flutter/pull/26798#issuecomment-455758159)
        - android-28
    before_script:
      - export BUILD_NAME=$TRAVIS_TAG
      - export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    script:
      - flutter doctor --android-licenses
      - yes | sdkmanager --update
      # - yes | sdkmanager --licenses
      - if [[ $TRAVIS_TAG == "" ]]; then flutter build apk; else flutter build apk --build-name $BUILD_NAME --build-number $BUILD_NUMBER; fi
    deploy:
      - provider: releases
        api_key: $GITHUB_TOKEN
        file: build/app/outputs/apk/release/app-release.apk
        skip_cleanup: true
        name: $TRAVIS_TAG
        on:
          tags: true
    after_deploy:
        - git branch $TRAVIS_TAG
        - git push https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_TAG

jobs:
    include:
    - stage: build
      <<: *build